apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: task-management-container
        image: task-management-service:latest
        ports:
        - containerPort: 8081
